authapp/urls.py
from django.urls import path, re_path, include
from django.views.generic import TemplateView

from .views import login, logout, register, edit, password, verify, telegram_login

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    # re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', verify, name='verify'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify'),
    # path('complete/telegram/', save_user_from_telegram, name='save_user_from_telegram'),
    path('telegram_login/', telegram_login, name='telegram_login'),
    path('profile/', TemplateView.as_view(template_name='profile.html'), name='profile'),
    path('auth/', include('social_django.urls', namespace='social')),
]

basketapp/urls.py
from django.urls import path
from .views import basket, basket_add, basket_remove, basket_edit

app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='view'),
    path('add/<int:pk>/', basket_add, name='add'),
    path('remove/<int:pk>/', basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket_edit, name='edit')
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
import mainapp.views as mainapp
from geekshop.views import index, contacts

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff'), name='admin_staff'),
    # path('products<int:pk>/', include('mainapp.urls', namespace='products'), name='products'),
    path('products/', include('mainapp.urls', namespace='products'), name='products'),
    path('basket/', include('basketapp.urls', namespace='basket'), name='basket'),
    path('order/', include('ordersapp.urls', namespace='order'), name='order'),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import path
from .views import products, product, products_ajax
from django.views.decorators.cache import cache_page

app_name = 'mainapp'

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', products, name='index'),
    path('category/<int:pk>/', products, name='category'),
    # path('category/<int:pk>/ajax/', cache_page(3600)(products_ajax)),
    path('category/<int:pk>/page/<int:page>/', cache_page(3600)(products), name='page'),
    # path('category/<int:pk>/page/<int:page>/ajax/', cache_page(3600)(products_ajax)),
    path('product/<int:pk>/', product, name='product'),

]

mainapp/models.py
from django.db import models

# Create your models here.
class ProductCategory(models.Model):
    name = models.CharField(
        verbose_name='имя',
        max_length=64,
        unique=True,
    )
    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )
    is_active = models.BooleanField(
        verbose_name='активна',
        default=True
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE,
        verbose_name='категория',
    )
    name = models.CharField(
        verbose_name='название продукта',
        max_length=128,
    )
    short_desc = models.CharField(
        max_length=256,
        blank=True,
        verbose_name='краткое описание',
    )
    image = models.ImageField(
        upload_to='products_images',
        blank=True,
    )
    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )
    price = models.DecimalField(
        verbose_name='цена',
        max_digits=8,
        decimal_places=2,
        default=0,
    )
    quantity = models.PositiveIntegerField(
        verbose_name='количество на складе',
        default=0,
    )
    is_active = models.BooleanField(
        verbose_name='активна',
        default=True
    )

    def __str__(self):
        return f'{self.name} ({self.category.name})'

    @staticmethod
    def get_items():
        # return Product.objects.filter(is_active=True).order_by('category', 'name')
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category').order_by('category', 'name')

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'

mainapp/views.py
import random

from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import ProductCategory, Product
from basketapp.models import Basket

from django.conf import settings
from django.core.cache import cache
from django.views.decorators.cache import cache_page

from django.template.loader import render_to_string
from django.http import JsonResponse


def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)     # Считаем все категории из справочника ("все" сформируем в HTML)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)       # Считаем все категории из справочника ("все" сформируем в HTML)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category').order_by('name')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category').order_by('name')


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_orederd_by_price():
    if settings.LOW_CACHE:
        key = 'products_orederd_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('price')


def get_products_in_category_orederd_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_orederd_by_price_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')


def get_absolute_url(self):
    return reverse('products', kwargs={'category_id': self.category_id})

# def get_basket(user):
#     if user.is_authenticated:
#         return Basket.objects.filter(user=user)
#     else:
#         return []

def get_hot_product():
    # products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
    products = get_products()
    return random.sample(list(products), 1)[0]

def get_same_products(hot_product):
    # same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]
    # same_products = Product.objects.filter(is_active=True, category__id=hot_product.category_id).select_related('category').exclude(pk=hot_product.pk)[:3]
    same_products = get_products_in_category_orederd_by_price(hot_product.category_id).exclude(pk=hot_product.pk)[:3]
    return same_products

@cache_page(3600)
def products(request, pk=None, page=1):
    # pk - вх. параметр для страницы products (фильтр для показа related products) если=None - пункт "ВСЕ"
    title = 'продукты'
    # links_menu = ProductCategory.objects.filter(is_active=True)     # Считаем все категории из справочника ("все" сформируем в HTML)
    links_menu = get_links_menu()
    # basket = get_basket(request.user)
    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    if pk is not None:
        if pk == 0:
            category = {'name': 'все', 'pk': pk}
            # products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category').order_by('name')
            products = get_products()
        else:
            # category = get_object_or_404(ProductCategory, pk=pk)
            category = get_category(pk)
            # products = Product.objects.all().filter(category__pk=pk).order_by('name')
            # products = Product.objects.filter(is_active=True, category__is_active=True, category__id=pk).select_related('category').order_by('name')
            products = get_products_in_category_orederd_by_price(pk)
    else:
        pk = 0
        category = ''
        products = ''

    paginator = Paginator(products, 3)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)

    context = {
        'title': title,
        'links_menu': links_menu,
        'category': category,
        'category_id': pk,
        'hot_product': hot_product,
        'related_products': same_products,
        'products': products_paginator,
        # 'basket': basket,
    }
    # return render(request, 'mainapp/products_list.html', context)
    return render(request, 'mainapp/products.html', context)


def products_ajax(request, pk=None, page=1):
    if request.is_ajax():
        links_menu = get_links_menu()

        if pk:
            if pk == '0':
                category = {
                    'pk': 0,
                    'name': 'все'
                }
                products = get_products_orederd_by_price()
            else:
                category = get_category(pk)
                products = get_products_in_category_orederd_by_price(pk)

            paginator = Paginator(products, 3)
            try:
                products_paginator = paginator.page(page)
            except PageNotAnInteger:
                products_paginator = paginator.page(1)
            except EmptyPage:
                products_paginator = paginator.page(paginator.num_pages)

            content = {
                'links_menu': links_menu,
                'category': category,
                'products': products_paginator,
            }

            result = render_to_string(
                'mainapp/includes/inc_products_list_content.html',
                context=content,
                request=request)

            return JsonResponse({'result': result})


def product(request, pk=None):
    title = 'продукт'
    # links_menu = ProductCategory.objects.filter(is_active=True)     # Считаем все категории из справочника ("все" сформируем в HTML)
    links_menu = get_links_menu()
    # basket = get_basket(request.user)

    # product = get_object_or_404(Product, pk=pk)
    product = get_product(pk)
    same_products = get_same_products(product)

    context = {
        'title': title,
        'links_menu': links_menu,
        'related_products': same_products,
        'product': product,
        # 'basket': basket,
    }
    return render(request, 'mainapp/product.html', context)

mainapp/templates/mainapp/includes/inc_categories_menu.html
<div class="links clearfix">
    <ul class="links-menu">
        <li>
            <a href="{% url 'products:category' 0 %}" class="{% if request.resolver_match.kwargs.pk == 0 %}
                active{% endif %}">
                Все
            </a>
        </li>
        {% for link in links_menu %}
        <li>
            <a href="{% url 'products:category' link.pk %}"
               class="{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}
                        active{% endif %}">{{ link.name }}
            </a>
        </li>
        {% endfor %}
    </ul>
</div>

<script type="text/javascript">
// старый вариант с предподготовкой в (vews.py):

<!-- links_menu = [{'href': '/products/category/0/', 'id': 0, 'name': 'все'}]  # дополним пунктом меню для всех категорий-->
<!-- for el in ProductCategory.objects.all():                        # Считаем все категории из справочника-->
<!--     links_menu.append({'href': '/products/category/'+str(el.id)+'/', 'id': el.id, 'name': el.name})-->

<!--<div class="links clearfix">-->
<!--    <ul class="links-menu">-->
<!--        {% for link in links_menu %}-->
<!--            <li><a href="{{ link.href }}" id="{{ link.id }}" class="{% if category_id == link.id %}active{% endif %}">{{ link.name }}</a></li>-->
<!--        {% endfor %}-->
<!--    </ul>-->
<!--</div>-->


</script>

mainapp/templates/mainapp/includes/inc_category_menu.html
<div class="links clearfix">
    <ul class="links-menu">
        <li>
            <a href="{% url 'products:category' 0 %}" class="{% if request.resolver_match.kwargs.pk == 0 %}
                active{% endif %}">
                Все
            </a>
        </li>
        {% for link in links_menu %}
        <li>
            <a href="{% url 'products:category' link.pk %}"
               class="{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}
                        active{% endif %}">{{ link.name }}
            </a>
        </li>
        {% endfor %}
    </ul>
</div>

<script type="text/javascript">
// старый вариант с предподготовкой в (vews.py):

<!-- links_menu = [{'href': '/products/category/0/', 'id': 0, 'name': 'все'}]  # дополним пунктом меню для всех категорий-->
<!-- for el in ProductCategory.objects.all():                        # Считаем все категории из справочника-->
<!--     links_menu.append({'href': '/products/category/'+str(el.id)+'/', 'id': el.id, 'name': el.name})-->

<!--<div class="links clearfix">-->
<!--    <ul class="links-menu">-->
<!--        {% for link in links_menu %}-->
<!--            <li><a href="{{ link.href }}" id="{{ link.id }}" class="{% if category_id == link.id %}active{% endif %}">{{ link.name }}</a></li>-->
<!--        {% endfor %}-->
<!--    </ul>-->
<!--</div>-->


</script>

mainapp/templates/mainapp/includes/inc_products_list_content.html
{% load static %}
{% load my_tags %}

<div class="featured mt-5 products_list" style="margin-top: 50px;">
    {% if category %}
    <div class="title clearfix">
        <h2>
            Категория: "{{ category.name|title }}"
        </h2>
    </div>
    <div class="paginator related" style="text-align: end;">
        {% if products.has_previous %}
        <a href="{% url 'products:page' category.pk products.previous_page_number %}">&larr;</a>
        {% endif %}
        <span class="current">
				страница {{ products.number }} из {{ products.paginator.num_pages }}
			  </span>
        {% if products.has_next %}
        <a href="{% url 'products:page' category.pk products.next_page_number %}">&rarr;</a>
        {% endif %}
    </div>
    <div class="related ">
        <table class="product_table" id="product_table_id">
            <tbody>
            <tr>
                <th class="table_head">Наименование</th>
                <th class="table_head">Категория</th>
                <th class="table_head">краткое описание</th>
                <th class="table_head">Цена</th>
                <th class="table_head" style='padding:0; white-space:normal;'><img
                        src="/static/geekshop/img/press_img.png" height=50px alt="Для просмотра нажмите"></th>
                <th class="table_head">подробности</th>
                <th class="table_head">корзина</th>
            </tr>
            {% for product in products %}
            <tr>
                <td>{{ product.name }}</td>
                <td>{{ product.category.name }}</td>
                <td>{{ product.short_desc }}</td>
                <td>{{ product.price }}</td>
                <td>
                    <img src="{{ product.image|media_folder_products }}" height=50 data-full_image_url="/media/{{ product.image }}"
                         alt="img">
                    <!--                                    <img src="/media/{{ product.image }}" height=50 data-full_image_url="/media/{{ product.image }}" onclick="openImage('/media/{{ product.image }}')" alt="img">-->
                </td>
                <td><a href="{% url 'products:product' product.pk %}">
                    <button class="button_add_to_basket" data-id="{{ product.pk }}">подробно</button>
                </a></td>
                <td>
                    {% autoescape off %}<a>{{ product|quantity_in_basket:basket }}</a>{% endautoescape %}
                    <a href="{% url 'basket:add' product.pk %}">
                        <button class="button_add_to_basket" data-id="{{ product.pk }}">в_корзину</button>
                    </a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% endif %}

    <div class="related">
        <div class="title clearfix">
            <h2>Похожие продукты</h2>
            <a class="explore" href="#">показать все <img src="/static/geekshop/img/arrow.png" alt=""></a>
        </div>
        <div class="related-products clearfix">
            {% for product_rel in related_products %}
            <div class="block">
                <a href="{% url 'products:product' product_rel.pk %}"><img src="/media/{{ product_rel.image }}"
                                                                           style="width: -webkit-fill-available"
                                                                           alt="">
                    <div class="text">
                        <img src="/static/geekshop/img/icon-hover.png" alt="img">
                        <h4>{{ product_rel.name }}</h4>
                        <p>{{ product_rel.short_desc }} </p>
                        <p>{{ product_rel.category.name }} </p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>