adminapp/urls.py
from django.urls import path
from .views import (
    # users,
    UserListView,
    # user_create,
    UserCreateView,
    # user_update,
    UserUpdateView,
    # user_update_password,
    UserUpdatePassword,
    # user_delete,
    UserDeleteView,
    categories,
    category_create,
    category_update,
    ProductCategoryUpdateView,
    category_delete,
    ProductCategoryDelete,
    products,
    product_create,
    # product_read,
    ProductDetailView,
    product_update,
    product_delete,
)
# from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView, PasswordResetDoneView

app_name = 'adminapp'

urlpatterns = [
    # path('users/read/', users, name='users'),
    # path('users/read/page/<int:page>/', users, name='users_page'),
    path('users/read/', UserListView.as_view(), name='users'),
    # path('users/create/', user_create, name='user_create'),
    path('users/create/', UserCreateView.as_view(), name='user_create'),
    # path('users/update/<int:pk>/', user_update, name='user_update'),
    path('users/update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    # path('users/delete/<int:pk>/', user_delete, name='user_delete'),
    path('users/delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    # path('users/update/password/<int:pk>/', user_update_password, name='user_update_password'),
    path('users/update/password/<int:pk>/', UserUpdatePassword, name='user_update_password'),
    path('users/update/password/', UserUpdatePassword, name='user_update_password'),

    path('categories/create/', category_create, name='category_create'),
    path('categories/read/', categories, name='categories'),
    # path('categories/update/<int:pk>/', category_update, name='category_update'),
    path('categories/update/<int:pk>/', ProductCategoryUpdateView.as_view(), name='category_update'),
    # path('categories/delete/<int:pk>/', category_delete, name='category_delete'),
    path('categories/delete/<int:pk>/', ProductCategoryDelete.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', product_create, name='product_create'),
    path('products/read/category/<int:pk>/', products, name='products'),
    path('products/read/category/<int:pk>/page/<int:page>/', products, name='products_page'),
    # path('products/read/<int:pk>/', product_read, name='product_read'),
    path('products/read/<int:pk>/', ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', product_update, name='product_update'),
    path('products/delete/<int:pk>/', product_delete, name='product_delete'),
]

authapp/urls.py
from django.urls import path, re_path, include
from django.views.generic import TemplateView

from .views import login, logout, register, edit, password, verify, telegram_login

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    # re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', verify, name='verify'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify'),
    # path('complete/telegram/', save_user_from_telegram, name='save_user_from_telegram'),
    path('telegram_login/', telegram_login, name='telegram_login'),
    path('profile/', TemplateView.as_view(template_name='profile.html'), name='profile'),
    path('auth/', include('social_django.urls', namespace='social')),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
import mainapp.views as mainapp
from geekshop.views import index, contacts

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff'), name='admin_staff'),
    # path('products<int:pk>/', include('mainapp.urls', namespace='products'), name='products'),
    path('products/', include('mainapp.urls', namespace='products'), name='products'),
    path('basket/', include('basketapp.urls', namespace='basket'), name='basket'),
    path('order/', include('ordersapp.urls', namespace='order'), name='order'),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import path
from .views import products, product, products_ajax
from django.views.decorators.cache import cache_page

app_name = 'mainapp'

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', products, name='index'),
    path('category/<int:pk>/', products, name='category'),
    # path('category/<int:pk>/ajax/', cache_page(3600)(products_ajax)),
    path('category/<int:pk>/page/<int:page>/', cache_page(3600)(products), name='page'),
    # path('category/<int:pk>/page/<int:page>/ajax/', cache_page(3600)(products_ajax)),
    path('product/<int:pk>/', product, name='product'),

]

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/views.py
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.contrib.admin.forms import AdminPasswordChangeForm
from django.db.models import F
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.db import connection

from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import user_passes_test
from django.views.generic import ListView, CreateView, DetailView, UpdateView, FormView, DeleteView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from authapp.models import ShopUser
from mainapp.models import Product, ProductCategory
from authapp.forms import ShopUserCreateForm, ShopUserEditForm
from adminapp.forms import ShopUserChangePasswordForm, ProductCategoryForm, ProductForm, ProductCategoryEditForm


# @user_passes_test(lambda u: u.is_superuser)
# def users(request, page=1):
#     title = 'админка/пользователи'
#     user_list = ShopUser.objects.all().order_by('-is_active', '-is_superuser', 'username')
#
#     paginator = Paginator(user_list, 5)
#     try:
#         objects_paginator = paginator.page(page)
#     except PageNotAnInteger:
#         objects_paginator = paginator.page(1)
#     except EmptyPage:
#         objects_paginator = paginator.page(paginator.num_pages)
#
#     context = {
#         'title': title,
#         'objects': objects_paginator
#     }
#     return render(request, 'adminapp/users.html', context)


class UserListView(LoginRequiredMixin, ListView):
    model = ShopUser  # единственный обязательный параметр
    template_name = 'adminapp/users.html'  # по умолчанию - 'adminapp/ShopUser_list.html'
    context_object_name = 'objects'  # по умолчанию...
    paginate_by = 5

    def get_queryset(self):  # для сортировки
        return ShopUser.objects.all().order_by('-is_active', '-is_superuser', 'username')

    def get_context_data(self):
        context = super(UserListView, self).get_context_data()
        title = 'админка/пользователи'
        context['title'] = title
        # context.update({'title': title})    # идентично
        return context


# @user_passes_test(lambda u: u.is_superuser)
# def user_create(request):
#     title = 'админка/создание пользователя'
#     if request.method == 'POST':
#         user_form = ShopUserRegisterForm(request.POST, request.FILES)
#         if user_form.is_valid():
#             user_form.save()
#             return HttpResponseRedirect(reverse('admin_staff:users_page', args='1'))
#     else:
#         user_form = ShopUserRegisterForm()
#
#     context = {
#         'title': title,
#         'type_operation': 'создание',
#         'update_form': user_form
#     }
#     return render(request, 'adminapp/user_update.html', context)

class UserCreateView(LoginRequiredMixin, CreateView):
    model = ShopUser
    form_class = ShopUserCreateForm
    template_name = 'adminapp/user_update.html'
    success_url = reverse_lazy('admin_staff:users')

    def get_context_data(self):
        context = super(UserCreateView, self).get_context_data()
        title = 'админка/создание пользователя'
        type_operation = 'создать'
        context.update({'title': title, 'type_operation': type_operation})
        # context.update({'title': title})
        # context.update({'type_operation': type_operation})
        return context


# @user_passes_test(lambda u: u.is_superuser)
# def user_update(request, pk):
#     title = 'админка/изменение пользователя'
#     user = get_object_or_404(ShopUser, pk=pk)
#     if request.method == 'POST':
#         user_form = ShopUserEditForm(request.POST, request.FILES, instance=user)
#         if user_form.is_valid():
#             user_form.save()
#             return HttpResponseRedirect(reverse('admin_staff:users_page', args='1'))
#     else:
#         user_form = ShopUserEditForm(instance=user)
#
#     context = {
#         'title': title,
#         'type_operation': 'изменение',
#         'user_avatar': user.avatar,
#         'form': user_form
#     }
#     return render(request, 'adminapp/user_update.html', context)

class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = ShopUser
    form_class = ShopUserEditForm
    template_name = 'adminapp/user_update.html'
    success_url = reverse_lazy('admin_staff:users')

    def get_context_data(self):
        context = super(UserUpdateView, self).get_context_data()
        title = 'админка/изменение пользователя'
        type_operation = 'изменить'
        user = get_object_or_404(ShopUser, pk=self.kwargs['pk'])
        context.update({'title': title, 'type_operation': type_operation, 'user_avatar': user.avatar})
        return context


# def user_update_password(request, pk=1):
#     title = 'Смена пароля'
#     user = get_object_or_404(ShopUser, pk=pk)
#
#     if request.method == 'POST':
#         password_form = ShopUserChangePasswordForm(request.POST, request.FILES, instance=user)
#         if password_form.is_valid():
#             password_form.save()
#
#             return HttpResponseRedirect(reverse('admin_staff:users_page', args='1'))
#     else:
#         password_form = ShopUserChangePasswordForm(instance=user)
#     context = {
#         'title': title,
#         'user_avatar': user.avatar,
#         'password_form': password_form
#     }
#     return render(request, 'adminapp/password.html', context)

class UserUpdatePassword(LoginRequiredMixin, PasswordChangeView):
    model = ShopUser
    # form_class = AdminPasswordChangeForm
    template_name = 'adminapp/password.html'
    success_url = reverse_lazy('admin_staff:users')
    #
    # def get_context_data(self):
    #     context = super(UserUpdateView, self).get_context_data()
    #     title = 'админка/изменение пользователя'
    #     type_operation = 'изменить'
    #     user = get_object_or_404(ShopUser, pk=self.kwargs['pk'])
    #     context.update({'title': title, 'type_operation': type_operation, 'user_avatar': user.avatar})
    #     return context


class UserUpdatePassword1(LoginRequiredMixin, FormView):
    model = ShopUser
    form_class = PasswordChangeForm
    template_name = 'adminapp/password.html'
    success_url = reverse_lazy('admin_staff:users')
    template_name = 'password_change.html'

    def get_form_kwargs(self):
        kwargs = super(UserUpdatePassword, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        if self.request.method == 'POST':
            kwargs['data'] = self.request.POST
        return kwargs

    def form_valid(self, form):
        form.save()
        # update_session_auth_hash(self.request, form.user)
        return super(UserUpdatePassword, self).form_valid(form)


# @user_passes_test(lambda u: u.is_superuser)
# def user_delete(request, pk):
#     title = 'админка/удаление пользователя'
#
#     user = get_object_or_404(ShopUser, pk=pk)
#     if request.method == 'POST':
#         # user.delete()
#         # вместо удаления лучше сделаем неактивным
#         user.is_active = False if user.is_active else True
#         user.save()
#         return HttpResponseRedirect(reverse('admin_staff:users_page', args='1'))
#     else:
#         user_form = ShopUserEditForm(instance=user)
#
#     type_operation = 'удалить пользователя' if user.is_active else 'восстановить активность'
#     context = {
#         'title': title,
#         'type_operation': type_operation,
#         'user_avatar': user.avatar,
#         'update_form': user_form
#     }
#     return render(request, 'adminapp/user_update.html', context)

class UserDeleteView(LoginRequiredMixin, UpdateView):
    model = ShopUser
    form_class = ShopUserEditForm
    template_name = 'adminapp/user_update.html'
    success_url = reverse_lazy('admin_staff:users')

    def get_context_data(self):
        context = super(UserDeleteView, self).get_context_data()
        title = 'админка/деактивация пользователя'
        user = get_object_or_404(ShopUser, pk=self.kwargs['pk'])
        type_operation = 'деактивировать' if user.is_active else 'активировать'
        context.update({'title': title, 'type_operation': type_operation, 'user_avatar': user.avatar})
        return context

    def post(self, request, *args, **kwargs):
        user = get_object_or_404(ShopUser, pk=self.kwargs['pk'])
        user.is_active = False if user.is_active else True
        user.save()
        # self.object = self.get_object()
        return super().post(request, *args, **kwargs)



@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    title = 'админка/категории'
    categories_list = ProductCategory.objects.all().order_by('-is_active', 'name')
    content = {
        'title': title,
        'objects': categories_list
    }
    return render(request, 'adminapp/categories.html', content)


@user_passes_test(lambda u: u.is_superuser)
def category_create(request):
    title = 'админка/создание категории'

    if request.method == 'POST':
        category_form = ProductCategoryForm(request.POST, request.FILES)
        if category_form.is_valid():
            category_form.save()
            return HttpResponseRedirect(reverse('admin_staff:categories'))
    else:
        category_form = ProductCategoryForm()

    context = {
        'title': title,
        'type_operation': 'создание',
        'update_form': category_form
    }
    return render(request, 'adminapp/category_update.html', context)

# Заменил вызов на CBV - ProductCategoryUpdateView
@user_passes_test(lambda u: u.is_superuser)
def category_update(request, pk):
    title = 'админка/изменение категории'

    category = get_object_or_404(ProductCategory, pk=pk)
    if request.method == 'POST':
        category_form = ProductCategoryForm(request.POST, request.FILES, instance=category)
        if category_form.is_valid():

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Категории</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fa fa-table mr-1"></i>
                Список
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Категория</th>
                            <th>Описание</th>
                            <th>Активная</th>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Категория</th>
                            <th>Описание</th>
                            <th>Активная</th>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for category in objects %}
                        <tr style="{% if not category.is_active %}opacity: .5;{% endif %}">
                            <td>{{ category.name }}</td>
                            <td>{{ category.description }}</td>
                            <td class="text-center">
                                {% if category.is_active %}
                                <i class="fa fa-check-circle"></i>
                                {% else %}
                                <i class="fa fa-times-circle"></i>
                                {% endif %}
                            </td>
                            <td class="text-center">
                                <button class="button_add_to_basket">
                                    <a href={% url 'admin_staff:products' category.pk %} style="color: #f9fafb">
                                    товары категории
                                    </a>
                                </button>
                            </td>
                            <td class="text-center">
                                {% if category.is_active %}
                                <button class="button_add_to_basket">
                                    <a href={% url 'admin_staff:category_update' category.pk %} style="color: #f9fafb">
                                    редактировать
                                    </a>
                                </button>
                                {% endif %}
                            </td>
                            <td class="text-center">
                                <button class="button_add_to_basket">
                                    <a href={% url 'admin_staff:category_delete' category.pk %} style="color: #f9fafb">
                                    {% if category.is_active %}
                                    удалить
                                    {% else %}
                                    восстановить
                                    {% endif %}
                                    </a>
                                </button>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="card-footer">
                <a href="{% url 'index' %}">
                    <button class="btn btn-success">на главную</button>
                </a>
                <a href="{% url 'adminapp:category_create' %}">
                    <button class="btn btn-success">Создать категорию</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}

adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Товары</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fa fa-table mr-1"></i>
                {{ category.name|title }}
            </div>

            <div class="paginator card-body" style="text-align: end;">
                {% if objects.has_previous %}
                <a href="{% url 'admin_staff:products_page' category.pk objects.previous_page_number %}">&larr;</a>
                {% endif %}
                <span class="current">
				страница {{ objects.number }} из {{ objects.paginator.num_pages }}
			  </span>
                {% if objects.has_next %}
                <a href="{% url 'admin_staff:products_page' category.pk objects.next_page_number %}">&rarr;</a>
                {% endif %}
            </div>

            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered text-center" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Изображение</th>
                            <th>Наименование</th>
                            <th>Краткое описание</th>
                            <th>Цена</th>
                            <th>Количество</th>
                            <th>Активный</th>
                            <th>Подробнее</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Изображение</th>
                            <th>Наименование</th>
                            <th>Краткое описание</th>
                            <th>Цена</th>
                            <th>Количество</th>
                            <th>Активный</th>
                            <th>Подробнее</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for product in objects %}
                        <tr style="{% if not product.is_active %}opacity: .5;{% endif %}">
                            <td>
                                <img src="{{ product.image|media_folder_products }}" height=50px
                                     data-full_image_url="/media/{{ product.image }}" alt="img">
                            </td>
                            <td>{{ product.name }}</td>
                            <td>{{ product.short_desc }}</td>
                            <td>{{ product.price }}</td>
                            <td>{{ product.quantity }}</td>
                            <td class="text-center">
                                {% if product.is_active %}
                                <i class="fa fa-check-circle"></i>
                                {% else %}
                                <i class="fa fa-times-circle"></i>
                                {% endif %}
                            </td>
                            <td class="text-center">
                                <button class="button_add_to_basket {% if not product.is_active %}invisible{% endif %}">
                                    <a href={% url 'admin_staff:product_read' product.pk %} style="color: #f9fafb">
                                    Подробно
                                    </a>
                                </button>
                            </td>
                            <td class="text-center">
                                <button class="button_add_to_basket {% if not product.is_active %}invisible{% endif %}">
                                    <a href={% url 'admin_staff:product_update' product.pk %} style="color: #f9fafb">
                                    Редактировать
                                    </a>
                                </button>
                            </td>
                            <td class="text-center">
                                <button class="button_add_to_basket">
                                    <a href={% url 'admin_staff:product_delete' product.pk %} style="color: #f9fafb">
                                    {% if product.is_active %}
                                    удалить
                                    {% else %}
                                    восстановить
                                    {% endif %}
                                    </a>
                                </button>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'index' %}">
                    <button class="btn btn-success">на главную</button>
                </a>
                <a href="{% url 'admin_staff:product_create' category.pk %}">
                    <button class="btn btn-success">Создать товар</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Пользователи</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fa fa-table mr-1"></i>
                Пользователи
            </div>

            {% if page_obj.has_other_pages %}
            <nav class="list-pages paginator card-body" style="text-align: end;">
                {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}" class="button_add_to_basket"> &lt; </a>
                {% endif %}
                {% for p in paginator.page_range %}
                {% if page_obj.number == p %}
                <a class="page-num page-num-selected" style="color: gray;"> {{ p }}</a>
                {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
                <a class="page-num" href="?page={{ p }}"> {{ p }} </a>
                {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" class="button_add_to_basket"> &gt; </a>
                {% endif %}
            </nav>
            <!--            <div class="paginator card-body" style="text-align: end;">-->
            <!--                {% if objects.has_previous %}-->
            <!--                <a href="{% url 'admin_staff:users_page' objects.previous_page_number %}">&larr;</a>-->
            <!--                {% endif %}-->
            <!--                <span class="current">-->
            <!--				страница {{ page_obj.number }} из {{ paginator.page_range }}-->
            <!--			  </span>-->
            <!--                {% if objects.has_next %}-->
            <!--                <a href="{% url 'admin_staff:users_page' objects.next_page_number %}">&rarr;</a>-->
            <!--                {% endif %}-->
            <!--            </div>-->
            {% endif %}

            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Аватарка</th>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Аватарка</th>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                            <th></th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for user in objects %}
                        {% if user.is_active %}
                        <tr>
                            {% else %}
                        <tr style="color: darkgray">
                            {% endif %}
                            <td><img src="{{ user.avatar|media_folder_users }}" height=50px alt="img"></td>
                            <td><a href="{% url 'admin_staff:user_update' user.id %}" style="color: dodgerblue">
                                {{ user.username }}</a></td>
                            <td>{{ user.first_name }}</td>
                            <td>{{ user.last_name }}</td>
                            <td>{{ user.email }}</td>
                            <td class="text-center">
                                {% if user.is_staff %}
                                <i class="fa fa-check-circle"></i>
                                {% else %}
                                <i class="fa fa-times-circle"></i>
                                {% endif %}
                            </td>
                            <td class="text-center">
                                {% if user.is_active %}
                                <i class="fa fa-check-circle"></i>
                                {% else %}
                                <i class="fa fa-times-circle"></i>
                                {% endif %}
                            </td>
                            <!--                            <td class="text-center">-->
                            <!--                                {% if user.is_active %}-->
                            <!--                                <button class="button_add_to_basket">-->
                            <!--                                    <a href={% url 'admin_staff:user_update_password' user.pk %} style="color: #f9fafb">-->
                            <!--                                    сменить пароль</a>-->
                            <!--                                </button>-->
                            <!--                                {% endif %}-->
                            <!--                            </td>-->
                            <td class="text-center">
                                <button class="button_add_to_basket">
                                    <a href={% url 'admin_staff:user_delete' user.pk %} style="color: #f9fafb">
                                    {% if user.is_active %}
                                    удалить
                                    {% else %}
                                    восстановить
                                    {% endif %}
                                    </a>
                                </button>
                            </td>

                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'index' %}">
                    <button class="btn btn-success">на главную</button>
                </a>
                <a href="{% url 'admin_staff:user_create' %}">
                    <button class="btn btn-success">Создать пользователя</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}