adminapp/urls.py
from django.urls import path
from .views import (
    # users,
    UserListView,
    # user_create,
    UserCreateView,
    # user_update,
    UserUpdateView,
    # user_update_password,
    UserUpdatePassword,
    # user_delete,
    UserDeleteView,
    categories,
    category_create,
    category_update,
    ProductCategoryUpdateView,
    category_delete,
    ProductCategoryDelete,
    products,
    product_create,
    # product_read,
    ProductDetailView,
    product_update,
    product_delete,
)
# from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView, PasswordResetDoneView

app_name = 'adminapp'

urlpatterns = [
    # path('users/read/', users, name='users'),
    # path('users/read/page/<int:page>/', users, name='users_page'),
    path('users/read/', UserListView.as_view(), name='users'),
    # path('users/create/', user_create, name='user_create'),
    path('users/create/', UserCreateView.as_view(), name='user_create'),
    # path('users/update/<int:pk>/', user_update, name='user_update'),
    path('users/update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    # path('users/delete/<int:pk>/', user_delete, name='user_delete'),
    path('users/delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    # path('users/update/password/<int:pk>/', user_update_password, name='user_update_password'),
    path('users/update/password/<int:pk>/', UserUpdatePassword, name='user_update_password'),
    path('users/update/password/', UserUpdatePassword, name='user_update_password'),

    path('categories/create/', category_create, name='category_create'),
    path('categories/read/', categories, name='categories'),
    # path('categories/update/<int:pk>/', category_update, name='category_update'),
    path('categories/update/<int:pk>/', ProductCategoryUpdateView.as_view(), name='category_update'),
    # path('categories/delete/<int:pk>/', category_delete, name='category_delete'),
    path('categories/delete/<int:pk>/', ProductCategoryDelete.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', product_create, name='product_create'),
    path('products/read/category/<int:pk>/', products, name='products'),
    path('products/read/category/<int:pk>/page/<int:page>/', products, name='products_page'),
    # path('products/read/<int:pk>/', product_read, name='product_read'),
    path('products/read/<int:pk>/', ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', product_update, name='product_update'),
    path('products/delete/<int:pk>/', product_delete, name='product_delete'),
]

authapp/urls.py
from django.urls import path, re_path, include
from django.views.generic import TemplateView

from .views import login, logout, register, edit, password, verify, telegram_login

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    # re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', verify, name='verify'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify'),
    # path('complete/telegram/', save_user_from_telegram, name='save_user_from_telegram'),
    path('telegram_login/', telegram_login, name='telegram_login'),
    path('profile/', TemplateView.as_view(template_name='profile.html'), name='profile'),
    path('auth/', include('social_django.urls', namespace='social')),
]

basketapp/urls.py
from django.urls import path
from .views import basket, basket_add, basket_remove, basket_edit

app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='view'),
    path('add/<int:pk>/', basket_add, name='add'),
    path('remove/<int:pk>/', basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket_edit, name='edit')
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
import mainapp.views as mainapp
from geekshop.views import index, contacts

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff'), name='admin_staff'),
    # path('products<int:pk>/', include('mainapp.urls', namespace='products'), name='products'),
    path('products/', include('mainapp.urls', namespace='products'), name='products'),
    path('basket/', include('basketapp.urls', namespace='basket'), name='basket'),
    path('order/', include('ordersapp.urls', namespace='order'), name='order'),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

geekshop/views.py
from django.shortcuts import render
# from mainapp.views import get_basket

# Create your views here.

def main(request):
    return render(request, 'geekshop/index.html')

def index(request):
    title = 'магазин'
    context = {
        'title': title,
        'slogan': 'горячее предложение',
        # 'basket': get_basket(request.user),
    }
    return render(request, 'geekshop/index.html', context)

def contacts(request):
    title = 'контакты'
    context = {
        'title': title,
        # 'basket': get_basket(request.user),
    }
    return render(request, 'geekshop/contact.html', context)

geekshop/templates/geekshop/includes/inc_footer.html
<div class="footer">
    <div class="clearfix">
        <div class="text-footer">
            <h3>контакты</h3>
        </div>
        <div class="text-footer">
            <h3>полезная информация</h3>
        </div>
        <div class="text-footer clearfix">
            <h3>Оставайтесь на связи</h3>
            <p>Подписаться на новости и рассылки</p>
            <form>
                <input type="email" name="email" placeholder="ваш email">
                <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
            </form>
        </div>
    </div>
    <p class="small">&copy; GB {% now "Y" %}</p>
    <div class="social">
        <a href="#" class="social1"></a>
        <a href="#" class="social2"></a>
        <a href="#" class="social3"></a>
        <a href="#" class="social4"></a>
    </div>
    <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
</div>

geekshop/templates/geekshop/includes/inc_main_menu.html
{% load my_tags %}


<div class="container">
    <div class="hero-white">
        <div class="header clearfix">

            <a href="/" class="logo"></a>

            <ul class="menu" style="display: flex; align-items: baseline;">
                <li><a href="/" class="{% if request.resolver_match.view_name == 'index' %}active{% endif %}">домой</a>
                </li>
                <li><a href="{% url 'products:index' %}"
                       class="{% if request.resolver_match.view_name == 'products:index' %}active{% endif %}">продукты</a>
                </li>
                <li><a href="{% url 'contacts' %}"
                       class="{% if request.resolver_match.view_name == 'contacts' %}active{% endif %}">контакты</a>
                </li>
                {% if user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" type="button"
                       id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{{ user.avatar|media_folder_users }}" style="width: 50px; border-radius: 50%;"
                             class="rounded-circle">
                        {{ user.first_name|default:'Пользователь' }}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <li><a class="dropdown-item" href="{% url 'auth:edit' %}">Профиль</a></li>
                        {% if user.is_staff %}
                        <li><hr class="dropdown-divider"></li>
                        <li>
                            <a class="dropdown-item inline-block" href="{% url 'admin_staff:users' %}">Менеджер</a>
                        </li>
                        {% endif %}
                        {% if user.is_superuser %}
                        <li>
                            <a class="dropdown-item" href="/admin/">Админка</a>
                        </li>
                        {% endif %}
                    </ul>
                </li>
                {% endif %}
                {% if basket %}
                <li>
                    <a href="{% url 'basket:view' %}" class="basket">
                        &#22291; - {{ basket.0.total_cost|floatformat:0 }}р ({{ basket.0.total_quantity }} шт.)</a>
                </li>
                {% endif %}
                <li>
                    {% if user.is_authenticated %}
                    <a href="{% url 'auth:logout' %}">выйти</a>
                    {% else %}
                    <a href="{% url 'auth:login' %}">войти</a>
                    {% endif %}
                </li>
            </ul>
            <a href="#" class="search"></a>
        </div>
    </div>
</div>