authapp/urls.py
from django.urls import path, re_path, include
from django.views.generic import TemplateView

from .views import login, logout, register, edit, password, verify, telegram_login

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    # re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', verify, name='verify'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify'),
    # path('complete/telegram/', save_user_from_telegram, name='save_user_from_telegram'),
    path('telegram_login/', telegram_login, name='telegram_login'),
    path('profile/', TemplateView.as_view(template_name='profile.html'), name='profile'),
    path('auth/', include('social_django.urls', namespace='social')),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
import mainapp.views as mainapp
from geekshop.views import index, contacts

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff'), name='admin_staff'),
    # path('products<int:pk>/', include('mainapp.urls', namespace='products'), name='products'),
    path('products/', include('mainapp.urls', namespace='products'), name='products'),
    path('basket/', include('basketapp.urls', namespace='basket'), name='basket'),
    path('order/', include('ordersapp.urls', namespace='order'), name='order'),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

ordersapp/urls.py
from django.urls import path

from ordersapp.views import OrderList #, order_forming_complete, OrderItemsCreate, OrderRead, OrderUpdate, OrderDelete
from ordersapp.views import order_forming_complete, OrderItemsCreate, OrderRead, OrderUpdate, OrderDelete, get_product_price


app_name = 'ordersapp'

urlpatterns = [
    path('', OrderList.as_view(), name='orders_list'),
    path('forming/complete/<int:pk>/', order_forming_complete, name='order_forming_complete'),
    path('create/', OrderItemsCreate.as_view(), name='order_create'),
    path('read/<int:pk>/', OrderRead.as_view(), name='order_read'),
    path('update/<int:pk>/', OrderUpdate.as_view(), name='order_update'),
    path('delete/<int:pk>/', OrderDelete.as_view(), name='order_delete'),
    path('product/<int:pk>/price/', get_product_price, name='get_price'),
]

ordersapp/models.py
from django.conf import settings
from django.db import models

from mainapp.models import Product

# Класс для корректировки остатков товаров
class OrderItemQuerySet(models.QuerySet):
    def delete(self, *args, **kwargs):
        for object in self:
            object.product.quantity += object.quantity
            object.product.save()
        super(OrderItemQuerySet, self).delete(*args, **kwargs)



class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAYD = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICE = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'отправлено в обработку'),
        (PROCEEDED, 'обрабатывается'),
        (PAYD, 'оплачен'),
        (READY, 'готов к выдаче'),
        (CANCEL, 'отменен'),
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    created = models.DateTimeField(
        verbose_name='создан',
        auto_now_add=True,
    )
    updated = models.DateTimeField(
        verbose_name='обновлен',
        auto_now=True,
    )
    status = models.CharField(
        verbose_name='статус',
        max_length=3,
        choices=ORDER_STATUS_CHOICE,
        default=FORMING,

    )
    is_active = models.BooleanField(
        verbose_name='активен',
        default=True,
    )
    class Meta:
        ordering = ('-created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return f'Текущий заказ: {self.id}'

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_product_type_quantity(self):
        items = self.orderitems.select_related()
        return len(items)

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity * x.product.price, items)))

    def delete(self):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity

        self.is_active = False
        self.status = 'CNC'
        self.save()

    def get_summary(self):
        items = self.orderitems.select_related()
        return {
            'total_cost': sum(list(map(lambda x: x.quantity * x.product.price, items))),
            'total_quantity': sum(list(map(lambda x: x.quantity, items))),

        }


class OrderItem(models.Model):

    objects = OrderItemQuerySet.as_manager()    # расширяем опции класса (при delete ваызывается...)
    order = models.ForeignKey(
        Order,
        related_name='orderitems',
        on_delete=models.CASCADE,
    )
    product = models.ForeignKey(
        Product,
        verbose_name='продукт',
        on_delete=models.CASCADE,
    )
    quantity = models.PositiveIntegerField(
        verbose_name='количество',
        default=0,
    )

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.filter(pk=pk).first()

    @property
    def get_product_cost(self):
        return self.product.price * self.quantity

    def delete(self):
        self.product.quantity += self.quantity      # вернем остатки в товаре
        self.product.save()
        super(self.__class__, self).delete()        # продолжим выполнение по встроенному сценарию

ordersapp/forms.py
from django import forms
from ordersapp.models import Order, OrderItem

from mainapp.models import Product


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemForm(forms.ModelForm):
    price = forms.CharField(label='цена', required=False)
    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            self.fields['product'].queryset = Product.get_items()
            field.widget.attrs['class'] = 'form-control'

ordersapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.db.models.signals import pre_save, pre_delete
from django.db.models import F, Q

from django.dispatch import receiver
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from ordersapp.models import Order, OrderItem

from basketapp.models import Basket
from ordersapp.forms import OrderItemForm

from mainapp.models import Product


class OrderList(LoginRequiredMixin, ListView):
    model = Order
    paginate_by = 5

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class OrderItemsCreate(LoginRequiredMixin, CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy('order:orders_list')

    def get_context_data(self, **kwargs):
        data = super(OrderItemsCreate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            basket_items = Basket.objects.filter(user=self.request.user)
            if len(basket_items):
                OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=len(basket_items))
                formset = OrderFormSet()
                for num, form in enumerate(formset.forms):
                    form.initial['product'] = basket_items[num].product
                    form.initial['quantity'] = basket_items[num].quantity
                    form.initial['price'] = basket_items[num].product.price
                    # basket_items[num].delete()      # можем так делать для  сработки в модели корректировки остатков товара
                basket_items.delete()
            else:
                formset = OrderFormSet()
        data['orderitems'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsCreate, self).form_valid(form)


class OrderUpdate(LoginRequiredMixin, UpdateView):
    model = Order
    fields = []
    # context_object_name = 'object'
    success_url = reverse_lazy('order:orders_list')

    def get_context_data(self, **kwargs):
        data = super(OrderUpdate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST, instance=self.object)
        else:
            formset = OrderFormSet(instance=self.object)
            for form in formset.forms:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.price

        data['orderitems'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderUpdate, self).form_valid(form)
    
    
class OrderDelete(LoginRequiredMixin, DeleteView):
    model = Order
    success_url = reverse_lazy('order:orders_list')
    
    
class OrderRead(LoginRequiredMixin, DetailView):
    model = Order
    template_name = 'ordersapp/order_detail.html'
    
    def get_context_data(self, **kwargs):
        context = super(OrderRead, self).get_context_data(**kwargs)
        context['title'] = 'заказ/просмотр'
        return context


def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SENT_TO_PROCEED
    order.save()
    return HttpResponseRedirect(reverse('order:orders_list'))


@receiver(pre_save, sender=OrderItem)
@receiver(pre_save, sender=Basket)      # дублирует работу model - закомментируем
def product_quantity_update_save(sender, update_fields, instance, **kwargs):
    if update_fields == 'quantity' or 'product':
        if instance.pk:
            # instance.refresh_from_db()
            instance.product.quantity -= instance.quantity - sender.get_item(instance.pk).quantity
            # instance.product.quantity = F('quantity') - instance.quantity - sender.get_item(instance.pk).quantity
        else:
            instance.product.quantity -= instance.quantity
        instance.product.save()
        print(instance.product.quantity)


@receiver(pre_delete, sender=OrderItem)
@receiver(pre_delete, sender=Basket)    # дублирует работу model - закомментируем
def product_quantity_update_delete(sender, instance, **kwargs):
    instance.product.quantity += instance.quantity
    instance.product.save()


def get_product_price(request, pk):
    if request.is_ajax():
        product = Product.objects.filter(pk=int(pk)).first()
        if product:
            return JsonResponse({'price': product.price})
        else:
            return JsonResponse({'price': 0})

ordersapp/templates/ordersapp/order_confirm_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="category_delete">
    <div class="h1">Уверены, что хотите удалить?</div>
    {% include 'ordersapp/includes/inc_order_summary.html' %}
    <form action="{% url 'order:order_delete' object.pk %}" method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
        <a href="{% url 'order:orders_list' %}">отмена</a>
    </button>
</div>
{% endblock %}

ordersapp/templates/ordersapp/order_detail.html
{% extends "adminapp/base.html" %}
{% load static %}
{% load my_tags %}

{% block content %}
{% include 'ordersapp/includes/inc_order_summary.html' %}
<div class="basket_list">
    {% for item in object.orderitems.select_related %}
    <div class="basket_record">
        <img src="{{ item.product.image|media_folder_products }}"
             height=50px alt="{{ item.product.short_desc }}">
        <span class="category_name">
                   {{ item.product.category.name }}
               </span>
        <span class="product_name">{{ item.product.name }}</span>
        <span class="product_price">
                   {{ item.product.price }}&nbspруб
               </span>
        <span class="product_quantitiy">
                   x {{ item.quantity }} шт.
               </span>
        <span class="product_cost">
                    = {{ item.get_product_cost }}&nbspруб
               </span>
    </div>
    {% endfor %}
</div>
{% include 'ordersapp/includes/inc_order_actions.html' %}

{% endblock %}

ordersapp/templates/ordersapp/order_form.html
{% extends "adminapp/base.html" %}
{% load static %}
{% load cache %}

{% block js %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="{% static 'ordersapp/script.js' %}"></script>
<script src="{% static 'ordersapp/jquery.formset.js' %}"></script>
{% endblock %}

{% block content %}
{% include 'ordersapp/includes/inc_order_summary.html' %}
<div class="order_form">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <table class="table">
            {{ orderitems.management_form }}
            {% for form in orderitems.forms %}
            {% if forloop.first %}
            <thead>
            <tr>
                {% for field in form.visible_fields %}
                <th class="{% cycle 'td1' 'td2' 'td3' %} order formset_td">
                    {{ field.label|capfirst }}
                </th>
                {% endfor %}
            </tr>
            </thead>
            {% endif %}
            <tr class="formset_row">
                {% for field in form.visible_fields %}
                <td class="{% cycle 'td1' 'td2' 'td3' %} order formset_td">
                    {% if forloop.first %}
                        {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}
                    {% endif %}
                    {{ field.errors.as_ul }}
                    {% if field.name != 'price' %}
                            {% cache 3600 orderitemform_product field.value %}
                                {{ field }}
                            {% endcache %}
                        {% else %}
                        {% if field.value %}
                            <span class="orderitems-{{forloop.parentloop.counter0}}-price">
                            {{ field.value }}
                            </span> руб
                        {% endif %}
                    {% endif %}

                </td>
                {% endfor %}
            </tr>
            {% endfor %}
        </table>
        <button type="submit" value="сохранить" class="btn btn-default btn-round form-control last">сохранить</button>
        {% include 'ordersapp/includes/inc_order_actions.html' %}
    </form>
</div>

{% endblock %}

ordersapp/templates/ordersapp/order_list.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Заказы</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fa fa-table mr-1"></i>
                Ваши заказы,
                {% if user.first_name %}
                {{ user.first_name|title}}
                {% else %}
                Пользователь
                {% endif %}
            </div>

            {% if page_obj.has_other_pages %}
            <nav class="list-pages paginator card-body" style="text-align: end;">
                {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}" class="button_add_to_basket"> &lt; </a>
                {% endif %}
                {% for p in paginator.page_range %}
                {% if page_obj.number == p %}
                <a class="page-num page-num-selected" style="color: gray;"> {{ p }}</a>
                {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
                <a class="page-num" href="?page={{ p }}"> {{ p }} </a>
                {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" class="button_add_to_basket"> &gt; </a>
                {% endif %}
            </nav>
            {% endif %}

            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Создан</th>
                            <th>Обновлен</th>
                            <th>Статус</th>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>Создан</th>
                            <th>Обновлен</th>
                            <th>Статус</th>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for item in object_list %}
                        {% if item.is_active %}
                        <tr>
                            {% else %}
                        <tr style="color: darkgray">
                            {% endif %}
                            <td class="td1 orders_list">{{ item.pk }}</td>
                            <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                            <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                            <td>{{ item.get_status_display }}</td>
                            <td class="text-center">
                                <button class="button_add_to_basket">
                                    <a href="{% url 'order:order_read' item.pk %}" style="color: #f9fafb">
                                        посмотреть
                                    </a>
                                </button>
                            </td>
                            <td class="text-center">
                                {% if item.status == 'FM' %}
                                <button class="button_add_to_basket">

                                    <a href="{% url 'order:order_update' item.pk %}" style="color: #f9fafb">
                                        редактировать
                                    </a>
                                </button>
                                {% endif %}
                            </td>
                            <td class="text-center">
                                {% if item.status == 'FM' %}
                                <button class="button_add_to_basket">
                                    <a href="{% url 'order:order_delete' item.pk %}" style="color: #f9fafb">
                                        удалить
                                    </a>
                                </button>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'index' %}">
                    <button class="btn btn-success">на главную</button>
                </a>
                <a href="{% url 'order:order_create' %}">
                    <button class="btn btn-success">Создать заказ</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}